#cloud-config
users:
  - name: ${ssh_username} # Use the dynamically passed username
    ssh-authorized-keys:
      - ssh-rsa ${public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

  - name: ${vm_name} # New user account with the same name as the VM
    passwd: $6$rounds=4096$somesalt$HASHED_PASSWORD # Replace with the hashed password for "pfe"
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

packages:
  - tree
